### ISSUE TITLE
make start invalid syntax

### ISSUE THREAD

**Issue by Onfire93** [stevenktruong/pug-bot#2]
Hey, when I try start a bot I get this error

`root@Discord:~/pug# make start
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    importlib.import_module("pug-bot")
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 669, in exec_module
  File "<frozen importlib._bootstrap_external>", line 775, in get_code
  File "<frozen importlib._bootstrap_external>", line 735, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/root/pug/pug-bot/__init__.py", line 43
    await pug.channel.send(f"`{pug.name}` was deleted for inactivity.")
                                                                     ^
SyntaxError: invalid syntax
make: Nothing to be done for 'start'.
`

![Untitled](https://user-images.githubusercontent.com/10382328/79640185-e37f3c00-8198-11ea-83e9-11e3accf3b7b.png)

**Comment by stevenktruong** [comment]
It looks like the issue is that you're running Python 3.5. I use [f-strings](https://www.google.com/search?q=f+strings+python&oq=f+strings+python&aqs=chrome..69i57j69i64l3.3770j0j7&sourceid=chrome&ie=UTF-8), which were introduced in Python 3.6.
